### ISSUE TITLE
Order detail JSON should contain product details

### ISSUE THREAD

**Issue by Arwask** [chicken-sloths/bangazon-api-sprint1#10]
Update the Order detail JSON object should contain all nested Product information.

For example:

```js
{
   OrderId: 21,
   CustomerId: 16,
   PaymentTypeId: 83,
   Products: [
      {
         ProductId: 156,
         Name: "Kite",
         Price: 14.25
         Quantity: 1
      },
      {
         ProductId: 212,
         Name: "Roller blades",
         Price: 88.99
         Quantity: 1
      }
   ]
}
```

**Comment by kenziebottoms** [comment]
Is this a joined query or do we want the OrderDetail object to contain Product information? Seems to violate single source of truth.

**Comment by TimAConner** [comment]
I have the same question.  Also, it says JSON object, but we are using SQL. Is JSON how the Order is being passed around in the JavaScript or does it want us to store it as JSON?

**Comment by jordan-castelloe** [comment]
I wanna help with this one!

**Comment by DavidLarsKetch** [comment]
Another update... Regarding @kenziebottoms comment: the first one. I'm understanding that the `JSON` returned from a query to `Orders` also makes a query of `Products_Orders` & from there `Products` to combine all the info.
