### ISSUE TITLE
Display Customers that haven't placed an Order

### ISSUE THREAD

**Issue by Arwask** [chicken-sloths/bangazon-api-sprint1#11]
By using the URL parameter `/customers/?active=false`, the JSON response should only contain customers that don't have any orders placed yet.

**Comment by jordan-castelloe** [comment]
Note to self: remember to store true/false as text in db since sqlite3 doesn't support booleans

**Comment by TimAConner** [comment]
We should decide what value we want to use for boolean in sqlite3.  0, 1, "true", "false"?

**Comment by DavidLarsKetch** [comment]
Just an update. This won't be handled by looking at a property `active` on a `customer`, but through joining `Customers` & `Orders`, returning `Customers` who do not appear on the `customer_id` prop of `Orders`

**Comment by DavidLarsKetch** [comment]
Refer to #92
