### ISSUE TITLE
Initialize data/fakers/products

### ISSUE THREAD

**Issue by DavidLarsKetch** [chicken-sloths/bangazon-api-sprint1#19]
In `data/fakers/products`, create: 
`productTypesFaker.js`, 
`productsFaker.js`, 
`customersFaker.js`, 
`paymentOptionsFaker.js`, 
`ordersFaker.js`, 
`productOrdersFaker.js`
`index.js`

Add default argument to generate function that is amount of rows to create. 
Each of these exports a function that would return an array of object.

Export these

**Comment by TimAConner** [comment]
Each of these exports a function that would return an array of object.

**Comment by TimAConner** [comment]
Add `index.js` to products folder.

**Comment by TimAConner** [comment]
Add default argument to generate function that is amount of rows to create.
